# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 0, size: 0.16, name: tag0},
    {id: 1, size: 0.16, name: tag1},
    {id: 2, size: 0.16, name: tag2},
    {id: 3, size: 0.16, name: tag3},
    {id: 4, size: 0.16, name: tag4},
    {id: 5, size: 0.16, name: tag5},
    {id: 6, size: 0.16, name: tag6},
    {id: 9, size: 0.16, name: tag9},
  ]
