prohibition_areas:
 # now define a line
   #Zone 1 (Front Material Room)
   - [[0.5, 9.6],
      [0.65, 2.5]]
   - [[0.7, 0],
      [0.95, -10]]
   
   - [[1.0, 2.5], #dodge door
      [1.0, 0]]   
   
   - [[0.2, 1.9], #dodge door
      [0.2, 1.5]]

   - [[1, -10.4],
      [62, -9.2]]
   - [[62, -9],
      [62, 10.6]]

   - [[-0.15, 3.5], #Wall MatRoom +
      [-0.35, 11]]
   - [[-0.06, 2.35], #Wall MatRoom -
      [0.18, -10]]

   - [[62, 7], #Second Line ZONE1
      [0.6, 6.5]]  

   - [[0, 10.65], #Wall Ai PP 10.55
      [62, 11.15]]  

   - [[20, 8.5], #Bound AIPP5 - AIPP7
      [20, 10]]  

   - [[30.5, 8.5], #Bound LineAIPP9
      [30.5, 11.5]]  

   - [[62, -9], #Bound Line12
      [62, -11]] 

   - [[0.6, 9.85], #AIPP2
      [5.05, 9.85]] 


   - [[6.5, 9.85], #AIPP2 to AIPP5 
      [16.7, 9.95]]

   - [[17.85, 9.95], #AIPP5 to AIPP7
      [21.45, 10.0]] 

   - [[22.6, 10.0], #AIPP7 to AIPP9
      [28.8, 10.1]] 
      
   - [[30.3, 10.35], #AIPP9 to end
      [62, 10.7]] 


#PROHIBIT AIPP2
   - [[5.45, 9.5], #1
      [5.45, 9.1]]
   - [[6.25, 9.5], #2
      [6.25, 9.1]]

#PROHIBIT AIPP5
   - [[16.95, 9.5], #1
      [16.95, 9.3]]
   - [[17.75, 9.5], #2
      [17.75, 9.3]]

#PROHIBIT AIPP7
   - [[21.65, 9.7], #1
      [21.65, 9.3]]
   - [[22.45, 9.7], #2
      [22.45, 9.3]]

#PROHIBIT AIPP9
   - [[29.05, 9.9], #1
      [29.05, 9.75]]
   - [[29.85, 9.9], #2
      [29.85, 9.75]]

   

   #Zone2
   #GreatWall
   - [[-1, -24],
      [7.5, -24]]
   - [[9.5, -24],
      [63, -22.6]]

   - [[51.3, -9], #Bound Line AIAS10
      [51.8, -17]]

   - [[7, -11.5], #Before Line AIAS1
      [7, -14]]

   - [[-1, -11.3], #Line AIAS1 
      [7.2, -11.20]]
   - [[-1, -11.15], #Line AIAS1 (secound)
      [7.2, -11.05]]

   - [[8.5, -11.2], #Line AIAS1 TO AIAS2-3
      [16.5, -11.1]]
   - [[8.5, -11.00], #Line AIAS1 TO AIAS2-3 (secound)
      [16.5, -10.93]]

   - [[17.5, -11.1], #Line AIAS2-3 TO AIAS 4-5
      [23.6, -10.95]]
   - [[17.5, -10.88], #Line AIAS2-3 TO AIAS 4-5 (secound)
      [23.6, -10.78]]

   - [[24.8, -10.95], #Line AIAS4-5 TO AIAS6
      [32.2, -10.8]]
   - [[24.8, -10.75], #Line AIAS4-5 TO AIAS6 (secound)
      [32.2, -10.63]]


   - [[33.4, -10.75], #Line AIAS6 TO AIAS8
      [39.6, -10.6]]
   - [[33.4, -10.57], #Line AIAS6 TO AIAS8 (secound)
      [39.6, -10.42]]

   
   - [[40.9, -10.7], #Line AIAS8 TO AIAS10
      [46.5, -10.55]]
   - [[40.9, -10.40], #Line AIAS8 TO AIAS10 (secound)
      [46.5, -10.3]]
   
   - [[41, -10.55], #Line12-1
      [41.05, -12]]

   #- [[49.5, -10.4], #Line12-2
   #   [49.55, -12]]

   - [[49, -10.38], #Line AIAS10 TO END
      [51, -10.35]]




#PROHIBIT AIAS1
   - [[7.5, -11.8], #11
      [7.5, -13]]
   # - [[8.3, -17], #12
   #    [8.3, -20]]
   # - [[8.5, -20.2], #13
   #    [8.5, -21.2]]
   - [[8.7, -12], #21
      [8.7, -13]]
   # - [[9.15, -15], #22
   #    [9.15, -19.5]]
   #Testnew matroom
   - [[8, -15], #11
      [8, -30]]
   - [[8.8, -15], #21
      [8.8, -34]]
   #################
# #PROHIBIT AIAS2-3
   - [[16.55, -11.8], #1
      [16.55, -12.7]]
   - [[17.35, -11.8], #2
      [17.35, -12.7]]
# #PROHIBIT AIAS4-5
   - [[24, -11.5], #1
      [24, -12.7]]
   - [[24.8, -11.5], #2
      [24.8, -12.7]]
# #PROHIBIT AIAS6
   - [[32.4, -11.2], #1
      [32.4, -11.3]]
   - [[33.2, -11.2], #2
      [33.2, -11.3]]
# #PROHIBIT AIAS8
   - [[40, -11.1], #1
      [40, -12.0]]
   - [[40.8, -11.1], #2
      [40.8, -12.0]]
# #PROHIBIT AIAS10
   - [[47.9, -10.8], #1
      [48.2, -19.5]]
   - [[48.7, -10.8], #2
      [49.0, -19.5]]