prohibition_areas:
 # now define a line
   #Zone 1 (Front Material Room)
   - [[1, 10],
      [1, -10]]
   - [[1, -10.4],
      [62, -9]]
   - [[62, -9],
      [62, 10.6]]

   - [[-0.3, 1], #Wall MatRoom +
      [-0.5, 11]]
   - [[-0.3, -0.75], #Wall MatRoom -
      [-0.1, -6]]

   - [[62, 9], #Second Line 2-4
      [1, 8.5]]  
   - [[46, 8.5], #Bound Line4
      [46, 11.5]]  
   - [[62, -9], #Bound Line12
      [62, -11]] 

   - [[1, 10], #Line1
      [5.2, 10]] 


   - [[6.8, 10], #Line1 to 2 
      [16.7, 10.2]]

  #  - [[18.2, 10.2], #Line2 to Junction
  #     [21, 10.28]] 

   - [[18.2, 10.2], #Line2 to line 3
      [32.81, 10.4]] 

  #  - [[22, 10.28], #Junction to Line3
  #     [32.81, 10.4]] 



   - [[34.31, 10.4], #Line4
      [40.81, 10.6]] 
      
   - [[42.31, 10.6], #Line4 to end
      [62, 10.8]] 
   

   #Zone2

   - [[-1, -19],
      [63, -17.6]]

   - [[51.3, -9], #Bound Line12
      [51.8, -17]]

   - [[7, -11.5], #Before Line5
      [7, -14]]

   - [[-1, -11.3], #Line5
      [7.5, -11.2]]

   - [[8.7, -11.2], #Line6-7
      [16.3, -11.1]]

   - [[17.3, -11.1], #Line8-9
      [24, -10.95]]

   - [[25, -10.95], #Line10
      [32.2, -10.8]]

   - [[33.2, -10.75], #Line11
      [40, -10.6]]

   
   - [[41, -10.55], #Line12
      [49.5, -10.4]]
   
   - [[41, -10.55], #Line12-1
      [41.05, -12]]

   - [[49.5, -10.4], #Line12-2
      [49.55, -12]]